<?php
//function one_form($form, &$form_state) {
//    $form['field_one'] = array(
//        '#type' => 'textfield',
//        '#title' => t('Text Field One'),
//        '#description' => t('Name'),
//        '#required' => TRUE,
//
//    );
//
//    $form['field_two'] = array(
//        '#type' => 'textfield',
//        '#title' => t('Text Field Two'),
//        '#description' => t('Surname'),
//
//    );
//    return $form;
//}
//
//
//function one_form_submit($form, &$form_state) {
//    drupal_set_message(t('Submitting values: @values', array('@values' => var_export($form_state['values'], TRUE))));
//}